#!/bin/bash
set -e
jobt_version=1.0.0
LIB=~/.jobt/binary/$jobt_version/lib

if [ ! -e "$LIB" ]; then
    java -cp jobt-downloader/jobt-downloader.jar jobt.JobtDownloader $jobt_version
fi

classpath=$(JARS=("$LIB"/*.jar); IFS=:; echo "${JARS[*]}")
java -cp $classpath jobt.Jobt
