#!/bin/bash
set -e
jobt_version=1.0.0
LIB=~/.jobt/binary/$jobt_version/lib

if [ ! -e "$LIB" ]; then
    java -cp jobt-downloader/jobt-downloader.jar jobt.JobtDownloader $jobt_version
fi

java -jar $LIB/jobt-$jobt_version.jar "$@"
