#!/usr/bin/env sh

set -e

loom_version=1.0.0

# Detect environment for special handling
cygwin=false
case "$(uname -s)" in
    CYGWIN*)
        cygwin=true
        ;;
esac

# Define location for Loom Library
if [ -z "$LOOM_USER_HOME" ]; then
    if $cygwin; then
        LOOM_USER_HOME="$LOCALAPPDATA/Loom/Loom"
    else
        LOOM_USER_HOME=~/.loom
    fi
fi

# Find the java executable
if [ -n "$JAVA_HOME" ] ; then
    javacmd="$JAVA_HOME/bin/java"
    if [ ! -x "$javacmd" ] ; then
        echo "ERROR: Can't execute $javacmd" >&2
        echo "Please ensure JAVA_HOME is configured correctly: $JAVA_HOME" >&2
        exit 1
    fi
else
    if ! which java >/dev/null 2>&1 ; then
        echo "ERROR: Can't find Java - JAVA_HOME is not set and no java was found in your PATH" >&2
        exit 1
    fi

    javacmd="$(which java)"
    echo "Warning: JAVA_HOME environment variable is not set - using $javacmd from path" >&2
fi

# Adjust paths for Cygwin
if $cygwin; then
    javacmd=$(cygpath --unix "$javacmd")
fi


loom_lib="$LOOM_USER_HOME/library/loom-$loom_version/lib/loom-$loom_version.jar"

test -e "$loom_lib" || "$javacmd" -jar loom-installer/loom-installer.jar

exec "$javacmd" $LOOM_OPTS --add-exports=java.base/jdk.internal.module=ALL-UNNAMED -jar "$loom_lib" "$@"
