#!/bin/sh
set -e
VERSION=1.0.0
LIB=~/.loom/binary/loom-$VERSION/lib/loom-$VERSION.jar

test -e "$LIB" || java -cp loom-downloader/loom-downloader.jar builders.loom.downloader.LoomDownloader

java -jar $LIB "$@"
